FORMAT: 1A

# Bootcamp

bootcamp is a simple API.

## Trigger [/api/v1/trigger]

### Send message to corresponding Redis channel [POST]

+ Response 201 (application/json)

    + Body

            {
                "query" : "language:javascript"
            }

## Repository [/api/v1/repository/{id}]

+ Parameters
    + id (number) - ID of the Repository in the form of an integer

### View a Repositories Detial [GET]

+ Response 200 (application/json)

        {
            {
                "id": 344,
                "owner": { 
                    "id": 410,
                    "login": 'developer',
                    "avatar_url": 'https://developer.com/avatar.png',
                    "html_url": 'https://github.com/developer',
                    "type": 'User' 
                },
                "full_name": '@risingstack/foo',
                "description": 'Very foo package, using bar technologies',
                "html_url": 'https://github.com/risingstack/foo',
                "language": 'Baz',
                "stargazers_count": 885 
            }
        }

## Repository [/api/v1/repository/{owner}/{name}]

+ Parameters
    + owner (string) - Name of the Repository owner in the form of a string
    + name (string) - Name of the Repository in the form of a string

### View a Repositories Detial [GET]

+ Response 200 (application/json)

        {
            {
                "id": 344,
                "owner": 
                { 
                    "id": 410,
                    "login": 'developer',
                    "avatar_url": 'https://developer.com/avatar.png',
                    "html_url": 'https://github.com/developer',
                    "type": 'User' 
                },
                "full_name": '@risingstack/foo',
                "description": 'Very foo package, using bar technologies',
                "html_url": 'https://github.com/risingstack/foo',
                "language": 'Baz',
                "stargazers_count": 885 
            }
        }
        
## Contributions [/api/v1/repository/{id}/contributions]

+ Parameters
    + id (number) - ID of the Contribution in the form of an integer

### View a Contributions Detial [GET]

+ Response 200 (application/json)

        [ 
            { 
                "user": 
                { 
                    "id": 594,
                    "login": 'developer',
                    "avatar_url": 'https://developer.com/avatar.png',
                    "html_url": 'https://github.com/developer',
                    "type": 'User' 
                },
                "repository":
                { 
                    "id": 668,
                    "owner": 594,
                    "full_name": '@risingstack/foo',
                    "description": 'Very foo package, using bar technologies',
                    "html_url": 'https://github.com/risingstack/foo',
                    "language": 'Baz',
                    "stargazers_count": 123 
                },
                "line_count": 873 
            },
        ...
        ]
        
## Repository [/api/v1/repository/{owner}/{name}/contributions]

+ Parameters
    + owner (string) - Name of the Contributions owner in the form of a string
    + name (string) - Name of the Contribution in the form of a string

### View a Repositories Detial [GET]

+ Response 200 (application/json)

        [ 
            { 
                "user": 
                { 
                    "id": 594,
                    "login": 'developer',
                    "avatar_url": 'https://developer.com/avatar.png',
                    "html_url": 'https://github.com/developer',
                    "type": 'User' 
                },
                "repository":
                { 
                    "id": 668,
                    "owner": 594,
                    "full_name": '@risingstack/foo',
                    "description": 'Very foo package, using bar technologies',
                    "html_url": 'https://github.com/risingstack/foo',
                    "language": 'Baz',
                    "stargazers_count": 123 
                },
                "line_count": 873 
            },
        ...
        ]